version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - mariadb
  mariadb:
    image: mariadb:10
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
