name: Staging
on:
  push:
    tags:
      - 'v*'

jobs:
  sync-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git fetch
          git checkout staging
          git merge ${{ github.ref }}
          git push
