name: Staging
on:
  push:
    tags:
      - 'v*'

jobs:
  sync-staging:
    name: Update staging branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: staging
          token: ${{ secrets.PAT_POKEN }}
          force: true
